rename={
    "all":{},
    "hgg":{
        "THU_ggH_wg1_Mig01":"THU_ggH_Mig01",
        "THU_ggH_wg1_Mig12":"THU_ggH_Mig12",
        "THU_ggH_wg1_Mu":"THU_ggH_Mu",
        "THU_ggH_wg1_PT120":"THU_ggH_PT120",
        "THU_ggH_wg1_PT60":"THU_ggH_PT60",
        "THU_ggH_wg1_Res":"THU_ggH_Res",
        "THU_ggH_wg1_qmtop":"THU_ggH_qmtop",
        "THU_qqH_JET01":"THU_VBF_Jet01",
        "THU_qqH_MJJ1000":"THU_VBF_Mjj1000",
        "THU_qqH_MJJ120":"THU_VBF_Mjj120",
        "THU_qqH_MJJ1500":"THU_VBF_Mjj1500",
        "THU_qqH_MJJ350":"THU_VBF_Mjj350",
        "THU_qqH_MJJ60":"THU_VBF_Mjj60",
        "THU_qqH_MJJ700":"THU_VBF_Mjj700",
        "THU_qqH_PTH200":"THU_VBF_PTH200",
        "THU_qqH_PTHJJ25":"THU_VBF_Pt25",
        "THU_qqH_Yield":"THU_VBF_Yield",
        "QCDscale_ggZH_had":"QCDscale_ggZH",
        "CMS_hgg_VH_scale_1jet_shape" : "VH_scale_1jet",
        "CMS_hgg_VH_scale_highmjj_highpt_shape" : "VH_scale_highmjj_highpt",
        "CMS_hgg_VH_scale_highmjj_lowpt_shape" : "VH_scale_highmjj_highpt",
        "CMS_hgg_VH_scale_lowmjj_shape" : "VH_scale_lowmjj",
        "CMS_hgg_WH_scale_highpt_shape" : "WH_scale_highpt",
        "CMS_hgg_WH_scale_lowpt_shape" : "WH_scale_lowpt",
        "CMS_hgg_ZH_scale_highpt_shape" : "ZH_scale_highpt",
        "CMS_hgg_ZH_scale_lowpt_shape" : "ZH_scale_lowpt",
        "CMS_hgg_ggH_scale_0jet_shape" : "ggH_scale_0jet",
        "CMS_hgg_ggH_scale_1jet_lowpt_shape" : "ggH_scale_1jet_lowpt",
        "CMS_hgg_ggH_scale_2jet_lowpt_shape" : "ggH_scale_2jet_lowpt",
        "CMS_hgg_ggH_scale_highpt_shape" : "ggH_scale_highpt",
        "CMS_hgg_ggH_scale_vbf_shape" : "ggH_scale_vbf",
        "CMS_hgg_ggH_scale_veryhighpt_shape" : "ggH_scale_very_highpt",
        "CMS_hgg_ttH_scale_highpt_shape" : "ttH_scale_highpt",
        "CMS_hgg_ttH_scale_lowpt_shape" : "ttH_scale_lowpt",
        "CMS_hgg_vbf_scale_0jet_shape" : "vbf_scale_0jet",
        "CMS_hgg_vbf_scale_1jet_shape" : "vbf_scale_1jet",
        "CMS_hgg_vbf_scale_highmjj_highpt_shape" : "vbf_scale_highmjj_highpt",
        "CMS_hgg_vbf_scale_highmjj_lowpt_shape" : "vbf_scale_highmjj_lowpt",
        "CMS_hgg_vbf_scale_lowmjj_shape" : "vbf_scale_lowmjj",
        ## TOT?
        ## ??
        #STXS_constrain_THU_qqH_JET01 lnN
        #STXS_constrain_THU_qqH_MJJ1000 lnN
        #STXS_constrain_THU_qqH_MJJ120 lnN
        #STXS_constrain_THU_qqH_MJJ1500 lnN
        #STXS_constrain_THU_qqH_MJJ350 lnN
        #STXS_constrain_THU_qqH_MJJ60 lnN
        #STXS_constrain_THU_qqH_MJJ700 lnN
        #STXS_constrain_THU_qqH_PTHJJ25 lnN
        #STXS_constrain_THU_qqH_Yield lnN
        "CMS_hgg_prefire_2016":"CMS_l1prefire_2016",
        "CMS_hgg_prefire_2017":"CMS_l1prefire_2017",
        ## JES
        #$zcat comb_2021_hgg.txt.gz  | grep CMS_scale_j | cut -d' ' -f 1| while read in ; do echo -n "\"$in\": \"" ; echo -n $in | sed 's:CMS_scale_j_\(.*\):CMS_scale_j_\L\1\E:g' | sed 's:CMS_scale_j_\(.*\)_y_\([0-9]*\):CMS_scale_j_\1_\2:g' ; echo '",' ; done
        "CMS_scale_j_Absolute": "CMS_scale_j_absolute",
        "CMS_scale_j_Absolute_y_2016": "CMS_scale_j_absolute_2016",
        "CMS_scale_j_Absolute_y_2017": "CMS_scale_j_absolute_2017",
        "CMS_scale_j_Absolute_y_2018": "CMS_scale_j_absolute_2018",
        "CMS_scale_j_BBEC1": "CMS_scale_j_bbec1",
        "CMS_scale_j_BBEC1_y_2016": "CMS_scale_j_bbec1_2016",
        "CMS_scale_j_BBEC1_y_2017": "CMS_scale_j_bbec1_2017",
        "CMS_scale_j_BBEC1_y_2018": "CMS_scale_j_bbec1_2018",
        "CMS_scale_j_EC2": "CMS_scale_j_ec2",
        "CMS_scale_j_EC2_y_2016": "CMS_scale_j_ec2_2016",
        "CMS_scale_j_EC2_y_2017": "CMS_scale_j_ec2_2017",
        "CMS_scale_j_EC2_y_2018": "CMS_scale_j_ec2_2018",
        "CMS_scale_j_FlavorQCD": "CMS_scale_j_flavorqcd",
        "CMS_scale_j_HF": "CMS_scale_j_hf",
        "CMS_scale_j_HF_y_2016": "CMS_scale_j_hf_2016",
        "CMS_scale_j_HF_y_2017": "CMS_scale_j_hf_2017",
        "CMS_scale_j_HF_y_2018": "CMS_scale_j_hf_2018",
        "CMS_scale_j_RelativeBal": "CMS_scale_j_relativebal",
        "CMS_scale_j_RelativeSample_y_2016": "CMS_scale_j_relativesample_2016",
        "CMS_scale_j_RelativeSample_y_2017": "CMS_scale_j_relativesample_2017",
        "CMS_scale_j_RelativeSample_y_2018": "CMS_scale_j_relativesample_2018",
        'CMS_hgg_ElectronID_2016' : 'CMS_eff_e_id_2016',
        'CMS_hgg_ElectronID_2017' : 'CMS_eff_e_id_2017',
        'CMS_hgg_ElectronID_2018' : 'CMS_eff_e_id_2018',
        'CMS_hgg_ElectronReco_2016' : 'CMS_eff_e_reco_2016',
        'CMS_hgg_ElectronReco_2017' : 'CMS_eff_e_reco_2017',
        'CMS_hgg_ElectronReco_2018' : 'CMS_eff_e_reco_2018',
        'CMS_hgg_MuonID_2016' : 'CMS_eff_m_id_2016',
        'CMS_hgg_MuonID_2017' : 'CMS_eff_m_id_2017',
        'CMS_hgg_MuonID_2018' : 'CMS_eff_m_id_2018',
        'CMS_hgg_MuonIso_2016' : 'CMS_eff_m_iso_2016',
        'CMS_hgg_MuonIso_2017' : 'CMS_eff_m_iso_2017',
        'CMS_hgg_MuonIso_2018' : 'CMS_eff_m_iso_2018',
        'CMS_hgg_MET_res_j_2016' : 'CMS_res_met_2016',
        'CMS_hgg_MET_res_j_2017' : 'CMS_res_met_2017',
        'CMS_hgg_MET_res_j_2018' : 'CMS_res_met_2018',
        'CMS_hgg_MET_scale_j_2016' : 'CMS_scale_met_2016',
        'CMS_hgg_MET_scale_j_2017' : 'CMS_scale_met_2017',
        'CMS_hgg_MET_scale_j_2018' : 'CMS_scale_met_2018',
        'CMS_hgg_MET_Unclustered_2016' : 'CMS_scale_met_unclustered_2016',
        'CMS_hgg_MET_Unclustered_2017' : 'CMS_scale_met_unclustered_2017',
        'CMS_hgg_MET_Unclustered_2018' : 'CMS_scale_met_unclustered_2018',
        },
    "hzz":{
       #"hzz_br":"BR_hzz",
       "THU_qqH_JET01":"THU_VBF_Jet01",
       "THU_qqH_Mjj1000":"THU_VBF_Mjj1000",
       "THU_qqH_Mjj120":"THU_VBF_Mjj120",
       "THU_qqH_Mjj1500":"THU_VBF_Mjj1500",
       "THU_qqH_Mjj350":"THU_VBF_Mjj350",
       "THU_qqH_Mjj60":"THU_VBF_Mjj60",
       "THU_qqH_Mjj700":"THU_VBF_Mjj700",
       "THU_qqH_PTH200":"THU_VBF_PTH200",
       "THU_qqH_PTH25":"THU_VBF_Pt25",
       "THU_qqH_Yield":"THU_VBF_Yield",
        },
    "htt":{
        "lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
        "lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
        "lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
        "lumi_13TeV_BBD":"lumi_13TeV_Beam_Beam_Deflection",
        "lumi_13TeV_BCC":"lumi_13TeV_Beam_Current_Calibration",
        "lumi_13TeV_DB":"lumi_13TeV_Dynamic_Beta",
        "lumi_13TeV_GS":"lumi_13TeV_Ghosts_And_Satellites",
        "lumi_13TeV_LS":"lumi_13TeV_Length_Scale",
        "lumi_13TeV_XY":"lumi_13TeV_X_Y_Factorization",
        "THU_qqH_25":"THU_VBF_Pt25",
        "THU_qqH_JET01":"THU_VBF_Jet01",
        "THU_qqH_Mjj1000":"THU_VBF_Mjj1000",
        "THU_qqH_Mjj120":"THU_VBF_Mjj120",
        "THU_qqH_Mjj1500":"THU_VBF_Mjj1500",
        "THU_qqH_Mjj350":"THU_VBF_Mjj350",
        "THU_qqH_Mjj60":"THU_VBF_Mjj60",
        "THU_qqH_Mjj700":"THU_VBF_Mjj700",
        "THU_qqH_PTH200":"THU_VBF_PTH200",
        "THU_qqH_TOT":"THU_VBF_Yield", #-> Yield
        "CMS_scale_j_Absolute": "CMS_scale_j_absolute",
        "CMS_scale_j_Absolute_2016": "CMS_scale_j_absolute_2016",
        "CMS_scale_j_Absolute_2017": "CMS_scale_j_absolute_2017",
        "CMS_scale_j_Absolute_2018": "CMS_scale_j_absolute_2018",
        "CMS_scale_j_BBEC1": "CMS_scale_j_bbec1",
        "CMS_scale_j_BBEC1_2016": "CMS_scale_j_bbec1_2016",
        "CMS_scale_j_BBEC1_2017": "CMS_scale_j_bbec1_2017",
        "CMS_scale_j_BBEC1_2018": "CMS_scale_j_bbec1_2018",
        "CMS_scale_j_EC2": "CMS_scale_j_ec2",
        "CMS_scale_j_EC2_2016": "CMS_scale_j_ec2_2016",
        "CMS_scale_j_EC2_2017": "CMS_scale_j_ec2_2017",
        "CMS_scale_j_EC2_2018": "CMS_scale_j_ec2_2018",
        "CMS_scale_j_FlavorQCD": "CMS_scale_j_flavorqcd",
        "CMS_scale_j_HF": "CMS_scale_j_hf",
        "CMS_scale_j_HF_2016": "CMS_scale_j_hf_2016",
        "CMS_scale_j_HF_2017": "CMS_scale_j_hf_2017",
        "CMS_scale_j_HF_2018": "CMS_scale_j_hf_2018",
        "CMS_scale_j_RelativeBal": "CMS_scale_j_relativebal",
        "CMS_scale_j_RelativeSample_2016": "CMS_scale_j_relativesample_2016",
        "CMS_scale_j_RelativeSample_2017": "CMS_scale_j_relativesample_2017",
        "CMS_scale_j_RelativeSample_2018": "CMS_scale_j_relativesample_2018",
        "QCDScale_ggHWW" : "QCDscale_ggH",
        "QCDScale_qqH" : "THU_VBF_Yield",
        "QCDScale_ttH" : "THU_ttH_Yield",
        "CMS_htt_boson_res_met_2016" : "CMS_res_met_2016",
        "CMS_htt_boson_res_met_2017" : "CMS_res_met_2017",
        "CMS_htt_boson_res_met_2018" : "CMS_res_met_2018",
    },
    "hzg": {
        "QCDscale_qqH" : "THU_VBF_Yield",
        "QCDscale_ttH" : "THU_ttH_Yield",
        "QCDscale_WH" : "THU_WH_inc",
        "QCDscale_ZH" : "THU_ZH_inc",
        "QCDscale_ggZH" : "THU_ggZH_inc",
        "CMS_PU_13TeV" : "CMS_pileup",
       },
    "hmm":{
        "lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
        "lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
        "lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
        "lumi_13TeV_BBD":"lumi_13TeV_Beam_Beam_Deflection",
        "lumi_13TeV_BCC":"lumi_13TeV_Beam_Current_Calibration",
        #"lumi_13TeV_DB":"lumi_13TeV_Dynamic_Beta",
        "lumi_13TeV_GS":"lumi_13TeV_Ghosts_And_Satellites",
        "lumi_13TeV_LS":"lumi_13TeV_Length_Scale",
        "lumi_13TeV_XY":"lumi_13TeV_X_Y_Factorization",
        "THU_VBF_TOT":"THU_VBF_Yield", ## only in ggH
        "QCDscale_ttH" : "THU_ttH_Yield",
        "QCDscale_qqH" : "THU_VBF_Yield",
        "QCDscale_WH" : "THU_WH_inc",
        "QCDscale_ZH" : "THU_ZH_inc",
        "QCDscale_ggZH" : "THU_ggZH_inc",
        ## BTag
        "CMS_btag_CfErr1":"CMS_btag_cferr1",
        "CMS_btag_CfErr2":"CMS_btag_cferr2",
        "CMS_btag_Hf":"CMS_btag_hf",
        "CMS_btag_HfStats1":"CMS_btag_hfstats1", ## in other channels this is split 16/17/18 CMS_btag_hfstats1_2016
        "CMS_btag_HfStats2":"CMS_btag_hfstats2",
        "CMS_btag_Lf":"CMS_btag_lf",
        "CMS_btag_LfStats1":"CMS_btag_lfstats1",
        "CMS_btag_LfStats2":"CMS_btag_lfstats2",
        #"CMS_btag_jes":"CMS_btag_jes",
        ### L1 prefire
        "CMS_prefiring_2016":"CMS_l1prefire_2016",
        "CMS_prefiring_2017":"CMS_l1prefire_2017",
        "prefiring_2016":"CMS_l1prefire_2016",
        "prefiring_2017":"CMS_l1prefire_2017",
        ## PU
        # "CMS_pileup_2016", puWeight_2016 -> VBF. Left outside alone. Make it clearer
        "puWeight_2016":"CMS_hmmvbf_pileup_2016",
        "puWeight_2017":"CMS_hmmvbf_pileup_2017",
        "puWeight_2018":"CMS_hmmvbf_pileup_2018",
        ## JES
        "CMS_scale_j_absolute": "CMS_scale_j_absolute",
        "CMS_scale_j_absolute_2016": "CMS_scale_j_absolute_2016",
        "CMS_scale_j_absolute_2017": "CMS_scale_j_absolute_2017",
        "CMS_scale_j_absolute_2018": "CMS_scale_j_absolute_2018",
        "CMS_scale_j_bbec1": "CMS_scale_j_bbec1",
        "CMS_scale_j_bbec1_2016": "CMS_scale_j_bbec1_2016",
        "CMS_scale_j_bbec1_2017": "CMS_scale_j_bbec1_2017",
        "CMS_scale_j_bbec1_2018": "CMS_scale_j_bbec1_2018",
        "CMS_scale_j_ec2": "CMS_scale_j_ec2",
        "CMS_scale_j_ec2_2016": "CMS_scale_j_ec2_2016",
        "CMS_scale_j_ec2_2017": "CMS_scale_j_ec2_2017",
        "CMS_scale_j_ec2_2018": "CMS_scale_j_ec2_2018",
        "CMS_scale_j_flavorQCD": "CMS_scale_j_flavorqcd",
        "CMS_scale_j_hf": "CMS_scale_j_hf",
        "CMS_scale_j_hf_2016": "CMS_scale_j_hf_2016",
        "CMS_scale_j_hf_2017": "CMS_scale_j_hf_2017",
        "CMS_scale_j_hf_2018": "CMS_scale_j_hf_2018",
        "CMS_scale_j_relativeBal": "CMS_scale_j_relativebal",
        "CMS_scale_j_relativeSample_2016": "CMS_scale_j_relativesample_2016",
        "CMS_scale_j_relativeSample_2017": "CMS_scale_j_relativesample_2017",
        "CMS_scale_j_relativeSample_2018": "CMS_scale_j_relativesample_2018",
    },
    "hww":{
        "lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
        "lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
        "lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
        "lumi_13TeV_BBDefl":"lumi_13TeV_Beam_Beam_Deflection",
        "lumi_13TeV_CurrCalib":"lumi_13TeV_Beam_Current_Calibration",
        "lumi_13TeV_DynBeta":"lumi_13TeV_Dynamic_Beta",
        "lumi_13TeV_Ghosts":"lumi_13TeV_Ghosts_And_Satellites",
        "lumi_13TeV_LSCale":"lumi_13TeV_Length_Scale",
        "lumi_13TeV_XYFact":"lumi_13TeV_X_Y_Factorization",
        "lumi_13TeV_correlated":"lumi_13TeV_Correlated",
        "lumi_13TeV_correlated_1718":"lumi_13TeV_Correlated1718",
        #"THU_qqH_EWK":"",
        "THU_qqH_JET01":"THU_VBF_Jet01",
        "THU_qqH_Mjj1000":"THU_VBF_Mjj1000",
        "THU_qqH_Mjj120":"THU_VBF_Mjj120",
        "THU_qqH_Mjj1500":"THU_VBF_Mjj1500",
        "THU_qqH_Mjj350":"THU_VBF_Mjj350",
        "THU_qqH_Mjj60":"THU_VBF_Mjj60",
        "THU_qqH_Mjj700":"THU_VBF_Mjj700",
        "THU_qqH_PTH200":"THU_VBF_PTH200",
        "THU_qqH_PTH25":"THU_VBF_Pt25",
        "THU_qqH_YIELD":"THU_VBF_Yield",
        "QCDscale_ttH" : "THU_ttH_Yield",
        "QCDscale_WH" : "THU_WH_inc",
        "QCDscale_ZH" : "THU_ZH_inc",
        "QCDscale_ggZH" : "THU_ggZH_inc",
        "QCDscale_qqbar_ACCEPT" : "QCDscale_qqH_ACCEPT",
        "QCDscale_gg_ACCEPT" : "QCDscale_ggH_ACCEPT",
        ### L1 prefire
        "CMS_eff_prefiring_2016":"CMS_l1prefire_2016",
        "CMS_eff_prefiring_2017":"CMS_l1prefire_2017",
        ## PU
        "CMS_PU_2016":"CMS_pileup_2016",
        "CMS_PU_2017":"CMS_pileup_2017",
        "CMS_PU_2018":"CMS_pileup_2018",
        ## JES
        #$zcat comb_2021_hww.txt.gz  | grep CMS_scale_JES | cut -d' ' -f 1| while read in ; do echo -n "\"$in\": \"" ; echo -n $in | sed 's:CMS_scale_JES\(.*\):CMS_scale_j_\L\1\E:g' ; echo '",' ; done
        "CMS_scale_JESAbsolute": "CMS_scale_j_absolute",
        "CMS_scale_JESAbsolute_2016": "CMS_scale_j_absolute_2016",
        "CMS_scale_JESAbsolute_2017": "CMS_scale_j_absolute_2017",
        "CMS_scale_JESAbsolute_2018": "CMS_scale_j_absolute_2018",
        "CMS_scale_JESBBEC1": "CMS_scale_j_bbec1",
        "CMS_scale_JESBBEC1_2016": "CMS_scale_j_bbec1_2016",
        "CMS_scale_JESBBEC1_2017": "CMS_scale_j_bbec1_2017",
        "CMS_scale_JESBBEC1_2018": "CMS_scale_j_bbec1_2018",
        "CMS_scale_JESEC2": "CMS_scale_j_ec2",
        "CMS_scale_JESEC2_2016": "CMS_scale_j_ec2_2016",
        "CMS_scale_JESEC2_2017": "CMS_scale_j_ec2_2017",
        "CMS_scale_JESEC2_2018": "CMS_scale_j_ec2_2018",
        "CMS_scale_JESFlavorQCD": "CMS_scale_j_flavorqcd",
        "CMS_scale_JESHF": "CMS_scale_j_hf",
        "CMS_scale_JESHF_2016": "CMS_scale_j_hf_2016",
        "CMS_scale_JESHF_2017": "CMS_scale_j_hf_2017",
        "CMS_scale_JESHF_2018": "CMS_scale_j_hf_2018",
        "CMS_scale_JESRelativeBal": "CMS_scale_j_relativebal",
        "CMS_scale_JESRelativeSample_2016": "CMS_scale_j_relativesample_2016",
        "CMS_scale_JESRelativeSample_2017": "CMS_scale_j_relativesample_2017",
        "CMS_scale_JESRelativeSample_2018": "CMS_scale_j_relativesample_2018",
        },
    "tth_multilepton":{
        "lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
        "lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
        "lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
        "lumi_13TeV_BBD":"lumi_13TeV_Beam_Beam_Deflection",
        "lumi_13TeV_BCC":"lumi_13TeV_Beam_Current_Calibration",
        "lumi_13TeV_DB":"lumi_13TeV_Dynamic_Beta",
        "lumi_13TeV_GS":"lumi_13TeV_Ghosts_And_Satellites",
        "lumi_13TeV_LS":"lumi_13TeV_Length_Scale",
        "lumi_13TeV_XY":"lumi_13TeV_X_Y_Factorization",
        # BTAG
        "CMS_ttHl16_btag_HFStats1":"CMS_btag_hfstats1_2016",
        "CMS_ttHl16_btag_HFStats2":"CMS_btag_hfstats2_2016",
        "CMS_ttHl16_btag_LFStats1":"CMS_btag_lfstats1_2016",
        "CMS_ttHl16_btag_LFStats2":"CMS_btag_lfstats2_2016",
        "CMS_ttHl17_btag_HFStats1":"CMS_btag_hfstats1_2017",
        "CMS_ttHl17_btag_HFStats2":"CMS_btag_hfstats2_2017",
        "CMS_ttHl17_btag_LFStats1":"CMS_btag_lfstats1_2017",
        "CMS_ttHl17_btag_LFStats2":"CMS_btag_lfstats2_2017",
        "CMS_ttHl18_btag_HFStats1":"CMS_btag_hfstats1_2018",
        "CMS_ttHl18_btag_HFStats2":"CMS_btag_hfstats2_2018",
        "CMS_ttHl18_btag_LFStats1":"CMS_btag_lfstats1_2018",
        "CMS_ttHl18_btag_LFStats2":"CMS_btag_lfstats2_2018",
        "CMS_ttHl_btag_HF":"CMS_btag_hf",
        "CMS_ttHl_btag_LF":"CMS_btag_lf",
        "CMS_ttHl_btag_CErr1":"CMS_btag_cferr1",
        "CMS_ttHl_btag_CErr2":"CMS_btag_cferr2",
        ### L1 prefire
        "CMS_ttHl16_L1PreFiring":"CMS_l1prefire_2016",
        "CMS_ttHl17_L1PreFiring":"CMS_l1prefire_2017",
        ### PU
        "CMS_ttHl_pileup":"CMS_pileup",
        ## JES
        #zcat comb_2021_tth_multilepton.txt.gz  | grep CMS_scale_j | cut -d' ' -f 1| while read in ; do echo -n "\"$in\": \"" ; echo -n $in | sed 's:CMS_scale_j_\(.*\):CMS_scale_j_\L\1\E:g' ; echo '",' ; done
        "CMS_scale_j_Absolute": "CMS_scale_j_absolute",
        "CMS_scale_j_Absolute_2016": "CMS_scale_j_absolute_2016",
        "CMS_scale_j_Absolute_2017": "CMS_scale_j_absolute_2017",
        "CMS_scale_j_Absolute_2018": "CMS_scale_j_absolute_2018",
        "CMS_scale_j_BBEC1": "CMS_scale_j_bbec1",
        "CMS_scale_j_BBEC1_2016": "CMS_scale_j_bbec1_2016",
        "CMS_scale_j_BBEC1_2017": "CMS_scale_j_bbec1_2017",
        "CMS_scale_j_BBEC1_2018": "CMS_scale_j_bbec1_2018",
        "CMS_scale_j_EC2": "CMS_scale_j_ec2",
        "CMS_scale_j_EC2_2016": "CMS_scale_j_ec2_2016",
        "CMS_scale_j_EC2_2017": "CMS_scale_j_ec2_2017",
        "CMS_scale_j_EC2_2018": "CMS_scale_j_ec2_2018",
        "CMS_scale_j_FlavorQCD": "CMS_scale_j_flavorqcd",
        "CMS_scale_j_HF": "CMS_scale_j_hf",
        "CMS_scale_j_HF_2016": "CMS_scale_j_hf_2016",
        "CMS_scale_j_HF_2017": "CMS_scale_j_hf_2017",
        "CMS_scale_j_HF_2018": "CMS_scale_j_hf_2018",
        "CMS_scale_j_RelativeBal": "CMS_scale_j_relativebal",
        "CMS_scale_j_RelativeSample_2016": "CMS_scale_j_relativesample_2016",
        "CMS_scale_j_RelativeSample_2017": "CMS_scale_j_relativesample_2017",
        "CMS_scale_j_RelativeSample_2018": "CMS_scale_j_relativesample_2018",
        ## Fix theory uncertainties
        "pdf_qg" : "pdf_Higgs_qg", #is only applied to tH procs..
        "pdf_qqH" : "pdf_Higgs_qqbar",
        "pdf_ggH" : "pdf_Higgs_gg",
        "pdf_ZH" : "pdf_Higgs_qqbar",
        "pdf_WH" : "pdf_Higgs_qqbar",
        "pdf_TTWW" : "pdf_ttWW",
        "QCDscale_ttH" : "THU_ttH_Yield",
        "QCDscale_WH" : "THU_WH_inc",
        "QCDscale_ZH" : "THU_ZH_inc",
        "QCDscale_ggZH" : "THU_ggZH_inc",
        "QCDscale_ttjets" : "QCDscale_ttbar",
        },
    "tth_hbb_partial": {
        "QCDscale_ttH" : "THU_ttH_Yield",
       },
    "tth_hbb":{
            "CMS_effTrigger_m_2016":"CMS_eff_m_trg_2016",
            "CMS_effTrigger_m_2017":"CMS_eff_m_trg_2017",
            "CMS_effTrigger_m_2018":"CMS_eff_m_trg_2018",
            ### L1 prefire
            "CMS_ttHbb_L1PreFiring_2016":"CMS_l1prefire_2016",
            "CMS_ttHbb_L1PreFiring_2017":"CMS_l1prefire_2017",
            ### PU
            "CMS_ttHbb_PU":"CMS_pileup",
            ## JES
            #zcat comb_2021_tth_hbb.txt.gz  | grep 'CMS_scale.*_j' | cut -d' ' -f 1| while read in ; do echo -n "\"$in\": \"" ; echo -n $in | sed 's:CMS_scale\(.*\)_j_\([0-9]*\):CMS_scale_j_\L\1\E_\2:g' | sed 's:CMS_scale\(.*\)_j$:CMS_scale_j_\L\1\E:g' ; echo '",' ; done
            "CMS_scaleAbsolute_j": "CMS_scale_j_absolute",
            "CMS_scaleAbsolute_j_2016": "CMS_scale_j_absolute_2016",
            "CMS_scaleAbsolute_j_2017": "CMS_scale_j_absolute_2017",
            "CMS_scaleAbsolute_j_2018": "CMS_scale_j_absolute_2018",
            "CMS_scaleBBEC1_j": "CMS_scale_j_bbec1",
            "CMS_scaleBBEC1_j_2016": "CMS_scale_j_bbec1_2016",
            "CMS_scaleBBEC1_j_2017": "CMS_scale_j_bbec1_2017",
            "CMS_scaleBBEC1_j_2018": "CMS_scale_j_bbec1_2018",
            "CMS_scaleEC2_j": "CMS_scale_j_ec2",
            "CMS_scaleEC2_j_2016": "CMS_scale_j_ec2_2016",
            "CMS_scaleEC2_j_2017": "CMS_scale_j_ec2_2017",
            "CMS_scaleEC2_j_2018": "CMS_scale_j_ec2_2018",
            "CMS_scaleFlavorQCD_j": "CMS_scale_j_flavorqcd",
            #"CMS_scaleHEM1516_j": "CMS_scale_j_hem1516",
            "CMS_scaleHF_j": "CMS_scale_j_hf",
            "CMS_scaleHF_j_2016": "CMS_scale_j_hf_2016",
            "CMS_scaleHF_j_2017": "CMS_scale_j_hf_2017",
            "CMS_scaleHF_j_2018": "CMS_scale_j_hf_2018",
            "CMS_scaleRelativeBal_j": "CMS_scale_j_relativebal",
            "CMS_scaleRelativeSample_j_2016": "CMS_scale_j_relativesample_2016",
            "CMS_scaleRelativeSample_j_2017": "CMS_scale_j_relativesample_2017",
            "CMS_scaleRelativeSample_j_2018": "CMS_scale_j_relativesample_2018",
            #"CMS_ttHbb_PDF" : "pdf_gg", # This is acceptance affect. Do we want to correlate with inclusive g pdf from other channels?
            "d60": "THU_ttH_mig60",
            "d120": "THU_ttH_mig120",
            "d200": "THU_ttH_mig200",
            "d300": "THU_ttH_mig300",
            "d450": "THU_ttH_mig450"
            },
    "hbb_boosted_partial":{
            ### PU
            "CMS_PU_2016":"CMS_pileup_2016",
            "CMS_PU_2017":"CMS_pileup_2017",
            "CMS_PU_2018":"CMS_pileup_2018",
    },
    "hbb_boosted_stxs":{
            ### L1 Prefire
            "CMS_L1Prefiring_2016":"CMS_l1prefire_2016",
            "CMS_L1Prefiring_2016APV":"CMS_l1prefire_2016",
            "CMS_L1Prefiring_2017":"CMS_l1prefire_2017",
            ### PU
            "CMS_hbb_PU_2016":"CMS_pileup_2016",
            "CMS_hbb_PU_2016APV":"CMS_pileup_2016",
            "CMS_hbb_PU_2017":"CMS_pileup_2017",
            "CMS_hbb_PU_2018":"CMS_pileup_2018",
            ## lumi
            "CMS_lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
            "CMS_lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
            "CMS_lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
    },    
    "hbb_boosted_incl":{
            ### L1 Prefire
            "CMS_L1Prefiring_2016":"CMS_l1prefire_2016",
            "CMS_L1Prefiring_2016APV":"CMS_l1prefire_2016",
            "CMS_L1Prefiring_2017":"CMS_l1prefire_2017",
            ### PU
            "CMS_hbb_PU_2016":"CMS_pileup_2016",
            "CMS_hbb_PU_2016APV":"CMS_pileup_2016",
            "CMS_hbb_PU_2017":"CMS_pileup_2017",
            "CMS_hbb_PU_2018":"CMS_pileup_2018",
            ## lumi
            "CMS_lumi_13TeV_2016":"lumi_13TeV_Uncorrelated_2016",
            "CMS_lumi_13TeV_2017":"lumi_13TeV_Uncorrelated_2017",
            "CMS_lumi_13TeV_2018":"lumi_13TeV_Uncorrelated_2018",
    },    
    "vhbb":{ ## swap them in for LEGACY cards
            ### PU
            "CMS_vhbb_puWeight":"CMS_pileup",
            ## JES
            #$zcat comb_2021_vhbb.txt.gz  | grep CMS_scale_j | cut -d' ' -f 1| while read in ; do echo -n "\"$in\": \"" ; echo -n $in | sed 's:CMS_scale_j_\(.*\):CMS_scale_j_\L\1\E:g' ; echo '",' ; done
            "CMS_scale_j_Absolute_13TeV": "CMS_scale_j_absolute",
            "CMS_scale_j_Absolute_2016_13TeV": "CMS_scale_j_absolute_2016",
            "CMS_scale_j_Absolute_2017_13TeV": "CMS_scale_j_absolute_2017",
            "CMS_scale_j_Absolute_2018_13TeV": "CMS_scale_j_absolute_2018",
            "CMS_scale_j_BBEC1_13TeV": "CMS_scale_j_bbec1",
            "CMS_scale_j_BBEC1_2016_13TeV": "CMS_scale_j_bbec1_2016",
            "CMS_scale_j_BBEC1_2017_13TeV": "CMS_scale_j_bbec1_2017",
            "CMS_scale_j_BBEC1_2018_13TeV": "CMS_scale_j_bbec1_2018",
            "CMS_scale_j_EC2_13TeV": "CMS_scale_j_ec2",
            "CMS_scale_j_EC2_2016_13TeV": "CMS_scale_j_ec2_2016",
            "CMS_scale_j_EC2_2017_13TeV": "CMS_scale_j_ec2_2017",
            "CMS_scale_j_EC2_2018_13TeV": "CMS_scale_j_ec2_2018",
            "CMS_scale_j_FlavorQCD_13TeV": "CMS_scale_j_flavorqcd",
            "CMS_scale_j_HF_13TeV": "CMS_scale_j_hf",
            "CMS_scale_j_HF_2016_13TeV": "CMS_scale_j_hf_2016",
            "CMS_scale_j_HF_2017_13TeV": "CMS_scale_j_hf_2017",
            "CMS_scale_j_HF_2018_13TeV": "CMS_scale_j_hf_2018",
            "CMS_scale_j_RelativeBal_13TeV": "CMS_scale_j_relativebal",
            "CMS_scale_j_RelativeSample_2016_13TeV": "CMS_scale_j_relativesample_2016",
            "CMS_scale_j_RelativeSample_2017_13TeV": "CMS_scale_j_relativesample_2017",
            "CMS_scale_j_RelativeSample_2018_13TeV": "CMS_scale_j_relativesample_2018",
    },

    "hinv":{
            "CMS_L1prefire_2016":"CMS_l1prefire_2016", ## will it work for param as well?
            "CMS_L1prefire_2017":"CMS_l1prefire_2017",
            ## btagging
            "CMS_btagl_2016":"CMS_btag_lf_2016",
            "CMS_btagl_2017":"CMS_btag_lf_2017",
            "CMS_btagl_2018":"CMS_btag_lf_2018",
            "CMS_btagb_2016":"CMS_btag_hf_2016",
            "CMS_btagb_2017":"CMS_btag_hf_2017",
            "CMS_btagb_2018":"CMS_btag_hf_2018",
            # assume sign is correct
            "CMS_eff_b_2016":"CMS_btag_hf_2016",
            "CMS_eff_b_2017":"CMS_btag_hf_2017",
            "CMS_eff_b_2018":"CMS_btag_hf_2018",
            "CMS_fake_b": "CMS_btag_lf",
            "CMS_fake_b_2016":"CMS_btag_lf_2016",
            "CMS_fake_b_2017":"CMS_btag_lf_2017",
            "CMS_fake_b_2018":"CMS_btag_lf_2018",
            ###
            #"jer_2017":"",
            #jer_2018
            "jesAbsolute":		     "CMS_scale_j_absolute_2016",
            "jesAbsolute_2017":		 "CMS_scale_j_absolute_2017",
            "jesAbsolute_2018":		 "CMS_scale_j_absolute_2018",
            "jesBBEC1":		         "CMS_scale_j_bbec1_2016",
            "jesBBEC1_2017":		 "CMS_scale_j_bbec1_2017",
            "jesBBEC1_2018":		 "CMS_scale_j_bbec1_2018",
            "jesEC2":		         "CMS_scale_j_ec2_2016",
            "jesEC2_2017":		     "CMS_scale_j_ec2_2017",
            "jesEC2_2018":		     "CMS_scale_j_ec2_2018",
            "jesFlavorQCD":		     "CMS_scale_j_flavorqcd",
            "jesHF":		         "CMS_scale_j_hf_2016",
            "jesHF_2017":		     "CMS_scale_j_hf_2017",
            "jesHF_2018":		     "CMS_scale_j_hf_2018",
            ## are these uncorrelated?
            "jesRelativeBal":		 "CMS_scale_j_relativebal",
            "jesRelativeBal_2017":   "CMS_scale_j_relativebal_2017",
            "jesRelativeBal_2018":   "CMS_scale_j_relativebal_2018",
            "jesRelativeSample_2017": "CMS_scale_j_relativesample_2017",
            "jesRelativeSample_2018": "CMS_scale_j_relativesample_2018",
            "CMS_scale_j_jesAbsolute"   :          "CMS_scale_j_absolute_2016",
            "CMS_scale_j_jesAbsolute_2017":        "CMS_scale_j_absolute_2017",
            "CMS_scale_j_jesAbsolute_2018":        "CMS_scale_j_absolute_2018",
            "CMS_scale_j_jesBBEC1" :               "CMS_scale_j_bbec1_2016",
            "CMS_scale_j_jesBBEC1_2017":           "CMS_scale_j_bbec1_2017",
            "CMS_scale_j_jesBBEC1_2018":           "CMS_scale_j_bbec1_2018",
            "CMS_scale_j_jesEC2":                  "CMS_scale_j_ec2_2016",
            "CMS_scale_j_jesEC2_2017":             "CMS_scale_j_ec2_2017",
            "CMS_scale_j_jesEC2_2018":             "CMS_scale_j_ec2_2018",
            "CMS_scale_j_jesFlavorQCD":            "CMS_scale_j_flavorqcd",
            "CMS_scale_j_jesHF":                   "CMS_scale_j_hf_2016",
            "CMS_scale_j_jesHF_2017":              "CMS_scale_j_hf_2017",
            "CMS_scale_j_jesHF_2018":              "CMS_scale_j_hf_2018",
            "CMS_scale_j_jesRelativeBal":          "CMS_scale_j_relativebal",
            "CMS_scale_j_jesRelativeSample_2016":  "CMS_scale_j_relativesample_2016",
            "CMS_scale_j_jesRelativeSample_2017":  "CMS_scale_j_relativesample_2017",
            "CMS_scale_j_jesRelativeSample_2018":  "CMS_scale_j_relativesample_2018",
            "QCDscale_WH" : "THU_WH_inc",
            "QCDscale_ZH" : "THU_ZH_inc",
            "QCDscale_ttH" : "THU_ttH_Yield",
            "QCDscale_ggH" : "THU_ggH_Mu",
            "QCDscale_ggZH" : "THU_ggZH_inc",
            "CMS_momres_e" : "CMS_res_e",
    },
    "vbfhbb":{
            "CMS_L1Prefire_2016" : "CMS_l1prefire_2016",
            "CMS_QCDscale" : "QCDscale_all_ACCEPT",
            "alphas_ggH" : "alphaS_ggH",
            "alphas_qqH" : "alphaS_qqH",
            "CMS_JES_2016" : "CMS_scale_j_2016", #param
            "CMS_JES_2018" : "CMS_scale_j_2018", #param
            "CMS_JER_2016" : "CMS_res_j_2016", #param
            "CMS_JER_2018" : "CMS_res_j_2018", #param
            "lumi_13TeV_2016" : "lumi_13TeV_Uncorrelated_2016",
            "lumi_13TeV_2018" : "lumi_13TeV_Uncorrelated_2018",
            "lumi_13TeV_1718" : "lumi_13TeV_Correlated1718",
            "lumi_13TeV_corr" : "lumi_13TeV_Correlated",
    },
}
##  copy htt into stxs and incl. TODO Check if the cards are coherents
rename["htt_incl"]=rename["htt"]
rename["htt_stxs"]=rename["htt"]
rename["hww_stxs"]=rename["hww"]
rename["vhbb_stxs"]=rename["vhbb"]
rename["vhbb_LEGACY"]=rename["vhbb"]

remove={
        "all":[],
        "hgg":["QCDscale_ggZH",'THU_ggH_stxs_0J_PTH10', 'THU_ggH_stxs_1J_PTH120', 'THU_ggH_stxs_1J_PTH60', 'THU_ggH_stxs_Boosted', 'THU_ggH_stxs_GE2J_HIGHMJJ_PTHJJ25', 'THU_ggH_stxs_GE2J_LOWMJJ_PTHJJ25', 'THU_ggH_stxs_GE2J_MJJ350', 'THU_ggH_stxs_GE2J_MJJ700', 'THU_ggH_stxs_GE2J_PTH120', 'THU_ggH_stxs_GE2J_PTH60', 'THU_ggH_stxs_Mig01', 'THU_ggH_stxs_Mig12', 'THU_ggH_stxs_PTH200', 'THU_ggH_stxs_PTH300', 'THU_ggH_stxs_PTH450', 'THU_ggH_stxs_PTH650', 'THU_ggH_stxs_Res', 'THU_ggH_stxs_Yield', 'STXS_constrain_THU_qqH_JET01', 'STXS_constrain_THU_qqH_MJJ1000', 'STXS_constrain_THU_qqH_MJJ120', 'STXS_constrain_THU_qqH_MJJ1500', 'STXS_constrain_THU_qqH_MJJ350', 'STXS_constrain_THU_qqH_MJJ60', 'STXS_constrain_THU_qqH_MJJ700', 'STXS_constrain_THU_qqH_PTHJJ25', 'STXS_constrain_THU_qqH_Yield', 'STXS_constrain_alphaS', 'STXS_constrain_pdf_Higgs'],
        #"hgg":['THU_ggH_Mig01', 'THU_ggH_Mig12', 'THU_ggH_Mu', 'THU_ggH_PT120', 'THU_ggH_PT60', 'THU_ggH_Res', 'THU_ggH_qmtop', 'STXS_constrain_THU_qqH_JET01', 'STXS_constrain_THU_qqH_MJJ1000', 'STXS_constrain_THU_qqH_MJJ120', 'STXS_constrain_THU_qqH_MJJ1500', 'STXS_constrain_THU_qqH_MJJ350', 'STXS_constrain_THU_qqH_MJJ60', 'STXS_constrain_THU_qqH_MJJ700', 'STXS_constrain_THU_qqH_PTHJJ25', 'STXS_constrain_THU_qqH_Yield', 'STXS_constrain_alphaS', 'STXS_constrain_pdf_Higgs']
        "hzz":["hzz_br"], ## the others BR_. are all dropped in prepareCombCards
        "tth_hbb":["dy"], # Replaced with THU_ttH_Yield in prepareComb
        "hzg":["BR_hzg"],
        "hww":["QCDscale_qqH"],
        }

flip={
    "all":[],
    "vhbb_stxs":[
     "QCDscale_ggZH",
     ],
    "hzz":[
        "CMS_eff_e",
        "CMS_eff_m",
        "THU_VBF_Jet01",
        "THU_VBF_Mjj1000",
        "THU_VBF_Mjj120",
        "THU_VBF_Mjj1500",
        "THU_VBF_Mjj350",
        "THU_VBF_Mjj60",
        "THU_VBF_Mjj700",
        "THU_VBF_PTH200",
        "THU_VBF_Pt25",
        "THU_VBF_Yield",
        "THU_ggH_Mig01",
        "THU_ggH_Mig12",
        "THU_ggH_Mu",
        "THU_ggH_PT120",
        "THU_ggH_PT60",
        "THU_ggH_Res",
        "THU_ggH_VBF2j",
        "THU_ggH_qmtop",
        ],
     "hgg":[
        "THU_ttH_Yield",
        "QCDscale_bbH",
        "QCDscale_ggZH",
        "QCDscale_tHW",
        "QCDscale_tHq",
        ]
    }
